/**
 * Created by kuo zi on 2016/10/14.
 */
const restUrl = {
    //平台用户列表
    memberList:{
        name:"会员列表",
        url:"member/list"
    },
    memberSave:{
        name:"会员删除",
        url:"member/save"
    },
    //收藏
    collectList:{
        name:"收藏列表",
        url:"collect/list"
    },
    collectMerchantList:{
        name:"用户收藏商户列表",
        url:"collectMerchant/list"
    },
    //兑换记录
    exchangeRecordList:{
        name:"兑换记录",
        url:"exchangeRecord/list"
    },
    //信用卡
    cardList:{
        name:"信用卡列表",
        url:"card/list"
    },
    cardSave:{
        name:"信用卡编辑、新增",
        url:"card/save"
    },
    cardDetail:{
        name:"信用卡详情",
        url:"card/get"
    },
    //银行
    bankList:{
        name:"银行卡列表",
        url:"bank/list"
    },
    bankSave:{
        name:"銀行修改新增",
        url:"bank/save"
    },
    bankDetail:{
        name:"銀行詳情",
        url:"bank/get"
    },
    //信用卡类型列表
    cardTypeList:{
        name:"信用卡类型列表",
        url:"cardType/list"
    },
    //电子货币包列表
    eMoneyList:{
        name:"电子货币包列表",
        url:"eMoney/list"
    },
    eMoneySave:{
        name:"電子貨幣包、新增、修改",
        url:"eMoney/save"
    },
    eMoneyDetail:{
        name:"電子貨幣卡詳情",
        url:"eMoney/get"
    },
    //信用卡類型管理
    cardTypeList:{
        name:"信用卡類型列表",
        url:"cardType/list"
    },
    cardTypeSave:{
        name:"信用卡類型修改、新增",
        url:"cardType/save"
    },
    cardTypeDetail:{
        name:"信用卡類型詳情",
        url:"cardType/get"
    },
    //信用卡优惠
    discountsChoiceList:{
        name:"信用卡優惠列表",
        url:"discountsChoice/page"
    },
    discountsChoiceSave:{
        name:"優惠修改、保存",
        url:"discountsChoice/save"
    },
    discountsChoiceDetail:{
        name:"信用卡優惠詳情",
        url:"discountsChoice/get"
    },
    //電子貨幣信用卡列表
    eCardList:{
        name:"電子貨幣信用卡列表",
        url:"eCard/list"
    },
    eCardSave:{
        name:"電子貨幣卡保存、修改",
        url:"eCard/save"
    },
    eCardDetail:{
        name:"電子貨幣卡詳情",
        url:"eCard/get"
    },
    //banner
    bannerList:{
        name:"banner列表",
        url:"banner/list"
    },
    bannerSave:{
        name:"修改保存",
        url:"banner/save"
    },
    bannerDetail:{
        name:"詳情",
        url:"banner/get"
    },
    //引導頁
    introductionList:{
        name:"引導頁列表",
        url:"introduction/list"
    },
    introductionDetail:{
        name:"詳情",
        url:"introduction/get"
    },
    introductionSave:{
        name:"新增、修改",
        url:"introduction/save"
    },
    //精選特惠
    discountsTypeList:{
        name:"列表",
        url:"discountsType/list"
    },
    discountsTypeSave:{
        name:"修改、新增",
        url:"discountsType/save"
    },
    discountsTypeDetail:{
        name:"詳情",
        url:"discountsType/get"
    },
    //禮物
    goodsList:{
        name:"禮物列表",
        url:"goods/list"
    },
    goodsSave:{
        name:"修改保存",
        url:"goods/save"
    },
    goodsDetail:{
        name:"詳情",
        url:"goods/get"
    },
    //系統消息
    messagesList:{
        name:"列表",
        url:"messages/list"
    },
    messagesSave:{
        name:"新增、編輯",
        url:"messages/save"
    },
    messagesDetail:{
        name:"詳情",
        url:"messages/get"
    },
    //報告
    reportList:{
        name:"報告列表",
        url:"report/list"
    },
    reportSave:{
        name:"修改刪除",
        url:"report/save"
    },
    reportDetail:{
        name:"报告详情",
        url:"report/get"
    },
    /** 用户*/
    userLogin:{
        name:"用户登录",
        url:"user/login"
    },
    userAuth:{
        name:"判断登录",
        url:"user/auth"
    },
    userSave:{
        name:"修改删除用户",
        url:"user/save"
    },
    userList:{
        name:"用户列表",
        url:"user/userList"
    },
    userLogout:{
        name:"用户退出",
        url:"user/logout"
    },
    userDetail:{
        name:"用户详情",
        url:"user/getUser"
    },
    // 商戶
    merchantList:{
        name:"商戶列表",
        url:"merchant/list"
    },
    merchantSave:{
        name:"新增修改商戶",
        url:"merchant/save"
    },
    merchantDetail:{
        name:"商戶詳情",
        url:"merchant/get"
    },
    // 信用卡迎新優惠
    cardDiscountsNewList:{
        name:"信用卡迎新優惠列表",
        url:"cardDiscountsNew/list"
    },
    cardDiscountsNewSave:{
        name:"信用卡迎新優惠新增修改",
        url:"cardDiscountsNew/save"
    },
    cardDiscountsNewDetail:{
        name:"信用卡迎新優惠詳情",
        url:"cardDiscountsNew/get"
    },

};

export default restUrl;
